var navbarSupportedContentHtml='';
navbarSupportedContentHtml += '<ul class="navbar-nav me-auto mb-2 mb-lg-0">';
navbarSupportedContentHtml += ' <li class="nav-item dropdown">';
navbarSupportedContentHtml += '   <a class="nav-link" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Asset Management</a>';
navbarSupportedContentHtml += '   <ul class="dropdown-menu" aria-labelledby="navbarDropdown">';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="issuance.html#anti-counterfeit">&#x1F430; Anti-counterfeiting</a></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="issuance.html#traceable">&#x1F426; Traceable</a></li>';
navbarSupportedContentHtml += '     <li><hr class="dropdown-divider"></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="issuance.html#reward">&#x1F414; Reward points</a></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="issuance.html#deactiveReward">&#x1F421; Deactive reward points</a></li>';
navbarSupportedContentHtml += '     <li><hr class="dropdown-divider"></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="issuance.html#properties">&#x1F41F; Additional Asset Information</a></li>';
navbarSupportedContentHtml += '     <li><hr class="dropdown-divider"></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="search.html">&#x1F50D;&nbsp; Search</a></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="utilities.html">&#x1F528; Utilities</a></li>';
navbarSupportedContentHtml += '   </ul></li>';
navbarSupportedContentHtml += ' <li class="nav-item dropdown">';
navbarSupportedContentHtml += '   <a class="nav-link" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Asset Transfer</a>';
navbarSupportedContentHtml += '   <ul class="dropdown-menu" aria-labelledby="navbarDropdown">';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="transfer.html#request">&#x1F41E; Request title token</a></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="transfer.html#transfer">&#x1F41A; Transfer title token</a></li>';
navbarSupportedContentHtml += '     <li><hr class="dropdown-divider"></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="transfer.html#voucherRecipient">&#x1F41D; Voucher: recipient</a></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="transfer.html#voucherSender">&#x1F41C; Voucher: sender</a></li>';
navbarSupportedContentHtml += '     <li><hr class="dropdown-divider"></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="transfer.html#tradeReward">&#x1F42B; Trade reward points</a></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="transfer.html#transfer">&#x1F418; Cashout reward points</a></li>';
navbarSupportedContentHtml += '     <li><hr class="dropdown-divider"></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="search.html">&#x1F50D;&nbsp; Search</a></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="utilities.html">&#x1F528; Utilities</a></li>';
navbarSupportedContentHtml += '   </ul></li>';
navbarSupportedContentHtml += ' <li class="nav-item dropdown">';
navbarSupportedContentHtml += '   <a class="nav-link" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Crypto Evidence</a>';
navbarSupportedContentHtml += '   <ul class="dropdown-menu" aria-labelledby="navbarDropdown">';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="evidence.html#genFileToken">&#x1F42C; Generate crypto evidence</a></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="evidence.html#decFileToken">&#x1F419; Validate crypto evidence</a></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="evidence.html#tokenize">&#x1F433; Tokenize crypto evidence</a></li>';
navbarSupportedContentHtml += '     <li><hr class="dropdown-divider"></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="evidence.html#token">&#x1F423; Generate message token</a></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="evidence.html#token">&#x1F424; Decode message token</a></li>';
navbarSupportedContentHtml += '   </ul></li>';
navbarSupportedContentHtml += ' <li class="nav-item dropdown">';
navbarSupportedContentHtml += '   <a class="nav-link" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Solutions</a>';
navbarSupportedContentHtml += '   <ul class="dropdown-menu" aria-labelledby="navbarDropdown">';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="howitworks.html#diti">&#x1F430; Anti-counterfeiting</a></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="howitworks.html#traceable">&#x1F426; Traceability</a></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="howitworks.html#reward">&#x1F427; Reward points</a></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="howitworks.html#evidence">&#x1F421; Crypto evidence</a></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="faq.html#traceable">&#x1F43E; FAQ</a></li>';
navbarSupportedContentHtml += '     <li><hr class="dropdown-divider"></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="security.html#dataIntegrity">&#x1F512; Data integrity</a></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="security.html#account">&#x1F511; Account safety</a></li>';
navbarSupportedContentHtml += '     <li><hr class="dropdown-divider"></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="download.html#sourcecode">&#x1F4E5; Download</a></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="download.html#instructions">&#x1F527; Instruction</a></li>';
navbarSupportedContentHtml += '     <li><hr class="dropdown-divider"></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="aboutcc14.html"><img src="images/logo-CC14.png" width="20" height="20" alt="langurage"> About CC14 blockchain</a></li>';
navbarSupportedContentHtml += '   </ul></li>';
navbarSupportedContentHtml += ' <li class="nav-item dropdown">';
navbarSupportedContentHtml += '   <a class="nav-link" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Marketplace</a>';
navbarSupportedContentHtml += '   <ul class="dropdown-menu" aria-labelledby="navbarDropdown">';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="shop.html">&#x1F429; Marketplace</a></li>';
navbarSupportedContentHtml += '     <li><hr class="dropdown-divider"></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="shoputilities.html#listing">&#x1F40E; Listing</a></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="shoputilities.html#delisting">&#x1F417; Delisting</a></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="shoputilities.html#price">&#x1F438; Update price</a></li>';
navbarSupportedContentHtml += '   </ul></li>';
navbarSupportedContentHtml += ' <li class="nav-item dropdown">';
navbarSupportedContentHtml += '   <a class="nav-link" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">&#x1F30F;</a>';
navbarSupportedContentHtml += '   <ul class="dropdown-menu" aria-labelledby="navbarDropdown">';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="index.html">&#x1F35A;中文</a></li>';
navbarSupportedContentHtml += '     <li style="opacity: 0.2;"><a class="dropdown-item" href="index_jp.html">&#x1F363; にほん</a></li>';
navbarSupportedContentHtml += '     <li style="opacity: 0.2;"><a class="dropdown-item" href="index_kr.html">&#x1F35C; 한국어</a></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="index.html">&#x1F354; English</a></li>';
navbarSupportedContentHtml += '     <li style="opacity: 0.2;"><a class="dropdown-item" href="index_es.html">&#x1F357; Español</a></li>';
navbarSupportedContentHtml += '     <li style="opacity: 0.2;"><a class="dropdown-item" href="index_fr.html">&#x1F35E; Français </a></li>';
navbarSupportedContentHtml += '     <li style="opacity: 0.2;"><a class="dropdown-item" href="index_it.html">&#x1F355; Italiano</a></li>';
navbarSupportedContentHtml += '     <li style="opacity: 0.2;"><a class="dropdown-item" href="index_de.html">&#x1F37A; Deutsch</a></li>';
navbarSupportedContentHtml += '   </ul>';
navbarSupportedContentHtml += '  </li>';
navbarSupportedContentHtml += '</ul>';

var footerHtml='';
footerHtml += '<div class="container-fluid" style="font-size:90%">';
footerHtml +=   '<div class="row">';
footerHtml +=     '<div class="col-12" style="text-align:center;margin-bottom: 5px;">';
footerHtml +=       '<a href="https://github.com/ditinow"><img src="images/logo-github.png" width="25" height="25" alt="github"></a>&nbsp;&nbsp;';
footerHtml +=       '<a href="index.html"><img src="images/logo-twitter.png" width="25" height="25" alt="twitter"></a>&nbsp;&nbsp;';
footerHtml +=       '<a href="index.html"><img src="images/logo-linkedin.png" width="25" height="25" alt="linkedin"></a>&nbsp;&nbsp;';
footerHtml +=       '<a href="index.html"><img src="images/logo-wechat.png" width="25" height="25" alt="wechat"></a>&nbsp;&nbsp;';
footerHtml +=       '<a href="index.html"><img src="images/logo-weibo.png" width="25" height="25" alt="weibo"></a>&nbsp;&nbsp;';
// footerHtml +=       '<a href="https://www.jelurida.com/ardor"><img src="images/logo-ardor.png" height="25" alt="language"></a>&nbsp;&nbsp;';
// footerHtml +=       '<a href="https://www.jelurida.com/ignis"><img src="images/logo-ignis.png" height="25" alt="language"></a>';
footerHtml +=     '</div>';
footerHtml +=   '</div>';
footerHtml +=   '<div class="row" style="text-align:center;background-color:#353A40; color:#fff;">';
footerHtml +=     '<div class="col-12 col-sm-12 col-md-6 col-lg-4">&#169;2021 CryptoC14 Copyright</div>';
footerHtml +=     '<div class="col-12 col-sm-12 col-md-6 col-lg-4">Donate ARDOR-49CE-CXZZ-3QHW-AH4JK</div>';
footerHtml +=     '<div class="col-12 col-sm-3 col-md-3 col-lg-4">'
footerHtml +=       '<a class="lightlink" href="aboutus.html">About us&nbsp;&nbsp;</a>'
footerHtml +=       '<a class="lightlink" href="contactus.html">&nbsp;Contact us&nbsp;&nbsp;</a>'
footerHtml +=       '<a class="lightlink" href="terms.html">&nbsp;Term&nbsp;&nbsp;</a>'
footerHtml +=       '<a class="lightlink" href="legal.html">&nbsp;Legal</a>'
footerHtml +=     '</div>';
footerHtml +=   '</div>';
footerHtml += '</div>';
