var navbarSupportedContentHtml='';
navbarSupportedContentHtml += '<ul class="navbar-nav me-auto mb-2 mb-lg-0">';
navbarSupportedContentHtml += ' <li class="nav-item dropdown">';
navbarSupportedContentHtml += '   <a class="nav-link" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">资产管理</a>';
navbarSupportedContentHtml += '   <ul class="dropdown-menu" aria-labelledby="navbarDropdown">';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="issuance.html#anti-counterfeit">&#x1F430; 区块链防伪</a></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="issuance.html#traceable">&#x1F426; 区块链溯源</a></li>';
navbarSupportedContentHtml += '     <li><hr class="dropdown-divider"></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="issuance.html#reward">&#x1F414; 发行积分奖励</a></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="issuance.html#deactiveReward">&#x1F421; 取消积分奖励</a></li>';
navbarSupportedContentHtml += '     <li><hr class="dropdown-divider"></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="issuance.html#properties">&#x1F41F; 资产附加信息</a></li>';
navbarSupportedContentHtml += '     <li><hr class="dropdown-divider"></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="search.html">&#x1F50D;&nbsp; 搜索</a></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="utilities.html">&#x1F528; 工具</a></li>';
navbarSupportedContentHtml += '   </ul></li>';
navbarSupportedContentHtml += ' <li class="nav-item dropdown">';
navbarSupportedContentHtml += '   <a class="nav-link" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">资产交易</a>';
navbarSupportedContentHtml += '   <ul class="dropdown-menu" aria-labelledby="navbarDropdown">';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="transfer.html#request">&#x1F41E; 申请产权通证</a></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="transfer.html#transfer">&#x1F41A; 转让产权通证</a></li>';
navbarSupportedContentHtml += '     <li><hr class="dropdown-divider"></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="transfer.html#voucherRecipient">&#x1F41D; 收据模式: 买家</a></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="transfer.html#voucherSender">&#x1F41C; 收据模式: 卖家</a></li>';
navbarSupportedContentHtml += '     <li><hr class="dropdown-divider"></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="transfer.html#tradeReward">&#x1F42B; 交易积分</a></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="transfer.html#transfer">&#x1F418; 兑现积分</a></li>';
navbarSupportedContentHtml += '     <li><hr class="dropdown-divider"></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="search.html">&#x1F50D;&nbsp; 搜索</a></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="utilities.html">&#x1F528; 工具</a></li>';
navbarSupportedContentHtml += '   </ul></li>';
navbarSupportedContentHtml += ' <li class="nav-item dropdown">';
navbarSupportedContentHtml += '   <a class="nav-link" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">区块链存证</a>';
navbarSupportedContentHtml += '   <ul class="dropdown-menu" aria-labelledby="navbarDropdown">';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="evidence.html#genFileToken">&#x1F42C; 生成文件证据</a></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="evidence.html#decFileToken">&#x1F419; 核实文件证据</a></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="evidence.html#tokenize">&#x1F433; 存证证据上链</a></li>';
navbarSupportedContentHtml += '     <li><hr class="dropdown-divider"></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="evidence.html#token">&#x1F423; 生成短语证据</a></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="evidence.html#token">&#x1F424; 核实短语证据</a></li>';
navbarSupportedContentHtml += '   </ul></li>';
navbarSupportedContentHtml += ' <li class="nav-item dropdown">';
navbarSupportedContentHtml += '   <a class="nav-link" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">工作原理</a>';
navbarSupportedContentHtml += '   <ul class="dropdown-menu" aria-labelledby="navbarDropdown">';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="howitworks.html#diti">&#x1F430; 区块链防伪</a></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="howitworks.html#traceable">&#x1F426; 区块链溯源</a></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="howitworks.html#reward">&#x1F427; 区块链积分</a></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="howitworks.html#evidence">&#x1F421; 区块链存证</a></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="faq.html#traceable">&#x1F43E; FAQ</a></li>';
navbarSupportedContentHtml += '     <li><hr class="dropdown-divider"></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="security.html#dataIntegrity">&#x1F512; 数据安全</a></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="security.html#account">&#x1F511; 钱包安全</a></li>';
navbarSupportedContentHtml += '     <li><hr class="dropdown-divider"></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="download.html#sourcecode">&#x1F4E5; 下载商用DApp</a></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="download.html#instructions">&#x1F527; 安装说明</a></li>';
navbarSupportedContentHtml += '     <li><hr class="dropdown-divider"></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="aboutcc14.html"><img src="images/logo-CC14.png" width="20" height="20" alt="langurage"> 关于 CC14 公链</a></li>';
navbarSupportedContentHtml += '   </ul></li>';
navbarSupportedContentHtml += ' <li class="nav-item dropdown">';
navbarSupportedContentHtml += '   <a class="nav-link" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">市场</a>';
navbarSupportedContentHtml += '   <ul class="dropdown-menu" aria-labelledby="navbarDropdown">';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="shop.html">&#x1F429; 进入市场</a></li>';
navbarSupportedContentHtml += '     <li><hr class="dropdown-divider"></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="shoputilities.html#listing">&#x1F40E; 货物上链</a></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="shoputilities.html#delisting">&#x1F417; 货物下链</a></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="shoputilities.html#price">&#x1F438; 更新售价</a></li>';
navbarSupportedContentHtml += '   </ul></li>';
navbarSupportedContentHtml += ' <li class="nav-item dropdown">';
navbarSupportedContentHtml += '   <a class="nav-link" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">&#x1F30F;</a>';
navbarSupportedContentHtml += '   <ul class="dropdown-menu" aria-labelledby="navbarDropdown">';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="http://cn.cryptoc14.com/">&#x1F35A;中文</a></li>';
navbarSupportedContentHtml += '     <li style="opacity: 0.2;"><a class="dropdown-item" href="index_jp.html">&#x1F363; にほん</a></li>';
navbarSupportedContentHtml += '     <li style="opacity: 0.2;"><a class="dropdown-item" href="index_kr.html">&#x1F35C; 한국어</a></li>';
navbarSupportedContentHtml += '     <li><a class="dropdown-item" href="http://www.cryptoc14.com/">&#x1F354; English</a></li>';
navbarSupportedContentHtml += '     <li style="opacity: 0.2;"><a class="dropdown-item" href="index_es.html">&#x1F357; Español</a></li>';
navbarSupportedContentHtml += '     <li style="opacity: 0.2;"><a class="dropdown-item" href="index_fr.html">&#x1F35E; Français </a></li>';
navbarSupportedContentHtml += '     <li style="opacity: 0.2;"><a class="dropdown-item" href="index_it.html">&#x1F355; Italiano</a></li>';
navbarSupportedContentHtml += '     <li style="opacity: 0.2;"><a class="dropdown-item" href="index_de.html">&#x1F37A; Deutsch</a></li>';
navbarSupportedContentHtml += '   </ul>';
navbarSupportedContentHtml += '  </li>';
navbarSupportedContentHtml += '</ul>';

var footerHtml='';
footerHtml += '<div class="container-fluid" style="font-size:90%">';
footerHtml +=   '<div class="row">';
footerHtml +=     '<div class="col-12" style="text-align:center;margin-bottom: 5px;">';
footerHtml +=       '<a href="index.html"><img src="images/logo-github.png" width="25" height="25" alt="github"></a>&nbsp;&nbsp;';
footerHtml +=       '<a href="index.html"><img src="images/logo-twitter.png" width="25" height="25" alt="twitter"></a>&nbsp;&nbsp;';
footerHtml +=       '<a href="index.html"><img src="images/logo-linkedin.png" width="25" height="25" alt="linkedin"></a>&nbsp;&nbsp;';
footerHtml +=       '<a href="index.html"><img src="images/logo-wechat.png" width="25" height="25" alt="wechat"></a>&nbsp;&nbsp;';
footerHtml +=       '<a href="index.html"><img src="images/logo-weibo.png" width="25" height="25" alt="weibo"></a>&nbsp;&nbsp;';
// footerHtml +=       '<a href="https://www.jelurida.com/ardor"><img src="images/logo-ardor.png" height="25" alt="language"></a>&nbsp;&nbsp;';
// footerHtml +=       '<a href="https://www.jelurida.com/ignis"><img src="images/logo-ignis.png" height="25" alt="language"></a>';
footerHtml +=     '</div>';
footerHtml +=   '</div>';
footerHtml +=   '<div class="row" style="text-align:center;background-color:#353A40; color:#fff;">';
footerHtml +=     '<div class="col-12 col-sm-12 col-md-6 col-lg-4">&#169;2021 CryptoC14 版权所有</div>';
footerHtml +=     '<div class="col-12 col-sm-12 col-md-6 col-lg-4">捐赠 ARDOR-49CE-CXZZ-3QHW-AH4JK</div>';
footerHtml +=     '<div class="col-12 col-sm-3 col-md-3 col-lg-4">'
footerHtml +=       '<a class="lightlink" href="aboutus.html">关于我们&nbsp;&nbsp;</a>'
footerHtml +=       '<a class="lightlink" href="contactus.html">&nbsp;联系我们&nbsp;&nbsp;</a>'
footerHtml +=       '<a class="lightlink" href="terms.html">&nbsp;使用条款&nbsp;&nbsp;</a>'
footerHtml +=       '<a class="lightlink" href="legal.html">&nbsp;法律声明</a>'
footerHtml +=     '</div>';
footerHtml +=   '</div>';
footerHtml += '</div>';
